### ISSUE TITLE
Download package: "Permission denied"

### ISSUE THREAD

**Issue by queckezz** [jfromaniello/Sublime-Package-Decontrol#4]
I'm not sure if the error comes from my end but whenever I try to install a package I get a "Permission Denied" error.

```
Traceback (most recent call last):
  File "/home/queckezz/.config/sublime-text-3/Packages/Package Decontrol/package_decontrol.py", line 23, in on_done
    self.download(name, tempfile, branch)
  File "/home/queckezz/.config/sublime-text-3/Packages/Package Decontrol/package_decontrol.py", line 45, in download
    self.download_with_curl(url, tempfile)
  File "/home/queckezz/.config/sublime-text-3/Packages/Package Decontrol/package_decontrol.py", line 59, in download_with_curl
    f = open(tempfile, 'w')
PermissionError: [Errno 13] Permission denied: 'jfromaniello-sublime-html-to-jade.zip'
```

**Comment by mattdesl** [comment]
same here

**Comment by magdakosior** [comment]
Me too.  im on sublime 2
